### ISSUE TITLE
failed to run

### ISSUE THREAD

**Issue by sherrytong** [liuyuemaicha/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-tensorflow#8]
Prepare Chitchat data in ./grl_data/
Reading development and training data (limit: 0).
b_set length:  0
b_set length:  6
b_set length:  2
b_set length:  0
Creating st_model model with fresh parameters
Created st_model model with fresh parameters
Creating bk_model model with fresh parameters
Created bk_model model with fresh parameters
Creating cc_model model with fresh parameters
Created cc_model model with fresh parameters
Traceback (most recent call last):
  File "/IR/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-tensorflow-master/grl_train.py", line 473, in <module>
    tf.app.run()
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/IR/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-tensorflow-master/grl_train.py", line 467, in main
    train()
  File "/IR/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-tensorflow-master/grl_train.py", line 261, in train
    rl_model = create_rl_model(sess, grl_config, False, grl_config.name_model)
  File "/IR/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-tensorflow-master/grl_train.py", line 99, in create_rl_model
    rl_model = grl_rnn_model.grl_model(grl_config=rl_config, name_scope=name_scope, forward=forward_only)
  File "/IR/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-tensorflow-master/grl_rnn_model.py", line 122, in __init__
    softmax_loss_function=softmax_loss_function)
  File "/IR/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-tensorflow-master/grl_seq2seq.py", line 477, in model_with_buckets
    decoder_inputs[:bucket[1]])
  File "/IR/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-tensorflow-master/grl_rnn_model.py", line 121, in <lambda>
    seq2seq=lambda x, y: seq2seq_f(x, y, tf.select(self.forward_only, True, False)),
  File "/IR/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-tensorflow-master/grl_rnn_model.py", line 98, in seq2seq_f
    dtype=dtype
  File "/IR/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-tensorflow-master/grl_seq2seq.py", line 401, in embedding_attention_seq2seq
    lambda: decoder(False))
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1776, in cond
    orig_res, res_t = context_t.BuildCondBranch(fn1)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1677, in BuildCondBranch
    r = fn()
  File "/IR/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-tensorflow-master/grl_seq2seq.py", line 400, in <lambda>
    lambda: decoder(True),
  File "/IR/Deep-Reinforcement-Learning-for-Dialogue-Generation-in-tensorflow-master/grl_seq2seq.py", line 397, in decoder
    return outputs + state_list
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/math_ops.py", line 813, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

I don't know how to solve it. Can you give me some idea?

**Comment by xinyuwang1126** [comment]
I encountered the same problem here..and I am using tf 0.12.0

**Comment by sjy980908** [comment]
> I encountered the same problem here..and I am using tf 0.12.0

I also met this kind of situation, have you solved it?
